#!/bin/bash
python generate_comparison_explanations.py --comparison_config "/home/nkondapa/PycharmProjects/RDX/comparison_configs/clip_vs_clipinat_inat_ar_guided/clip_vs_clipinat_inat_ar_guided_gator.json" --comparison_output_root outputs/clip_vs_clipinat_inat_ar_guided --save_m0_representation  --save_m1_representation 
python generate_comparison_explanations.py --comparison_config "/home/nkondapa/PycharmProjects/RDX/comparison_configs/clip_vs_clipinat_inat_ar_guided/clip_vs_clipinat_inat_ar_guided_corvid.json" --comparison_output_root outputs/clip_vs_clipinat_inat_ar_guided --save_m0_representation  --save_m1_representation 
python generate_comparison_explanations.py --comparison_config "/home/nkondapa/PycharmProjects/RDX/comparison_configs/clip_vs_clipinat_inat_ar_guided/clip_vs_clipinat_inat_ar_guided_maple.json" --comparison_output_root outputs/clip_vs_clipinat_inat_ar_guided --save_m0_representation  --save_m1_representation 



python interactive_cluster_viz_general.py --rdx_output_dir outputs/clip_vs_clipinat_inat_ar_guided/clip_vs_clipinat_inat_ar_guided_gator/inatdl_subset_grouped/rdx_nb_lb_spectral --repr_0_path outputs/clip_vs_clipinat_inat_ar_guided/clip_vs_clipinat_inat_ar_guided_gator/m0_rep.pkl --repr_1_path outputs/clip_vs_clipinat_inat_ar_guided/clip_vs_clipinat_inat_ar_guided_gator/m1_rep.pkl --repr_0_name "CLIP" --repr_1_name "CLIP-iNat" --image_paths outputs/clip_vs_clipinat_inat_ar_guided/clip_vs_clipinat_inat_ar_guided_gator/image_paths.pkl --data_root ./data/inat_subset/ --K 12 --K_matrix 12 --thumb_size 224
python interactive_cluster_viz_general.py --rdx_output_dir outputs/clip_vs_clipinat_inat_ar_guided/clip_vs_clipinat_inat_ar_guided_corvid/inatdl_subset_grouped/rdx_nb_lb_spectral --repr_0_path outputs/clip_vs_clipinat_inat_ar_guided/clip_vs_clipinat_inat_ar_guided_corvid/m0_rep.pkl --repr_1_path outputs/clip_vs_clipinat_inat_ar_guided/clip_vs_clipinat_inat_ar_guided_corvid/m1_rep.pkl --repr_0_name "CLIP" --repr_1_name "CLIP-iNat" --image_paths outputs/clip_vs_clipinat_inat_ar_guided/clip_vs_clipinat_inat_ar_guided_corvid/image_paths.pkl --data_root ./data/inat_subset/ --K 12 --K_matrix 12 --thumb_size 224
python interactive_cluster_viz_general.py --rdx_output_dir outputs/clip_vs_clipinat_inat_ar_guided/clip_vs_clipinat_inat_ar_guided_maple/inatdl_subset_grouped/rdx_nb_lb_spectral --repr_0_path outputs/clip_vs_clipinat_inat_ar_guided/clip_vs_clipinat_inat_ar_guided_maple/m0_rep.pkl --repr_1_path outputs/clip_vs_clipinat_inat_ar_guided/clip_vs_clipinat_inat_ar_guided_maple/m1_rep.pkl --repr_0_name "CLIP" --repr_1_name "CLIP-iNat" --image_paths outputs/clip_vs_clipinat_inat_ar_guided/clip_vs_clipinat_inat_ar_guided_maple/image_paths.pkl --data_root ./data/inat_subset/ --K 12 --K_matrix 12 --thumb_size 224
